contentColumnType: string(400)
fieldGroup: 9c70ac35-6a75-42f6-9a20-9a1496034cb7
handle: landingTitle
instructions: ''
name: 'Landing Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
