contentColumnType: text
fieldGroup: 610cc453-a2d4-4022-b46c-122711d3dae3
handle: siteName
instructions: ''
name: 'Site Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
