contentColumnType: string
fieldGroup: 4a701bf0-19f0-45e2-8512-e529e6a5ce99
handle: socials
instructions: ''
name: Socials
searchable: false
settings:
  contentTable: '{{%matrixcontent_socials}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
